[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Show the prompt playground
prompt_playground = true

# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = true

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Automatically tag threads the first message of the thread.
auto_tag_thread = true

# Literal AI connection to log all your sessions on the Literal AI platform
[features.literalai]
# The server URL of your Literal AI instance
# server = ""
# The API key for your Literal AI instance
# api_key = ""

[UI]
# Name of the app and chatbot.
name = "Process Mining Analysis Tool"

# Show the readme while the thread is empty.
show_readme_as_default = true

# Description of the app and chatbot. This is used for HTML tags.
description = "Analyze your process mining data through an interactive chat interface"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
# github = ""

# Show the sidebar with chat history and settings
show_sidebar = true

# Specify a CSS file that can be used to customize the user interface.
# The CSS file should be placed in the .chainlit directory.
custom_css = "custom.css"

# Specify a Javascript file that can be used to customize the user interface.
# The Javascript file should be placed in the .chainlit directory.
custom_js = "custom.js"

# Override default MUI light theme. (Check theme.py)
[UI.theme]
    #layout = "wide"
    #font_family = "Inter, sans-serif"
[UI.theme.light]
    #background = "#FAFAFA"
    #paper = "#FFFFFF"

    [UI.theme.light.primary]
        #main = "#F80061"
        #dark = "#980039"
        #light = "#FFE7EB"

# Override default MUI dark theme. (Check theme.py)
[UI.theme.dark]
    #background = "#FAFAFA"
    #paper = "#FFFFFF"

    [UI.theme.dark.primary]
        #main = "#F80061"
        #dark = "#980039"
        #light = "#FFE7EB"


[meta]
generated_by = "2.6.0"